import { Service } from '@angular/core';
import { FlightDetails } from '../../features/home/model/types';

@Service()
export class FlightApi {
  flightDetails: FlightDetails[] = [
    {
      flightNumber: '6E-2131',
      airlineName: 'IndiGo',
      airlineLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB1wabUbuhvcAgjzXGao7BqdMTI7Saymkhs5usV5_gHe6f9XQrGeR12Kk&s=10',
      departureTime: '06:15',
      departureDate: 'Sun, 30 May',
      arrivalTime: '08:25',
      arrivalDate: 'Sun, 30 May',
      departureAirport: {
        code: 'PNQ',
        name: 'Pune',
        airport: 'Pune International Airport',
      },
      arrivalAirport: {
        code: 'DEL',
        name: 'New Delhi',
        airport: 'Indira Gandhi International Airport, Terminal T3',
      },
      duration: '2h 10m',
      stops: 'Non-stop',
      stopsCount: 0,
      stopAirports: [],
      baggage: {
        cabin: '7 KGS/Adult',
        checkIn: '15 KGS/Adult',
      },
      onTimePercentage: 95,
      priceINR: 5499,
      promoCode: 'INDIGO200',
      discountText: 'Flat ₹200 off',
      fareOptions: [
        {
          id: 'saver',
          title: 'Saver',
          subtitle: 'Standard Hand & Check-in Baggage',
          priceINR: 5499,
          badge: 'Best Value',
          hoverContent: 'Includes standard seats and up to 7kg cabin baggage.',
          features: ['Cabin Baggage 7kg', 'Standard Seat Selection'],
        },
        {
          id: 'flexi',
          title: 'Flexi Plus',
          subtitle: 'Flexible changes & extra comfort',
          priceINR: 6899,
          badge: 'Popular',
          hoverContent: 'Free seat selection and zero cancellation fee options.',
          features: ['Free Seat Selection', 'Zero Cancellation Fee', 'Cabin 7kg + Check-in 15kg'],
        },
      ],
    },
    {
      flightNumber: 'AI-854',
      airlineName: 'Air India',
      airlineLogo:
        'https://play-lh.googleusercontent.com/0sWgYJnF1vMlSfP7g2bHe3XAWCUph1XCSgAo-RgURNwCfh4pPNNKN2DqlFwMg3KCKznDDh3RxjdjCUJFGi79',
      departureTime: '11:25',
      departureDate: 'Sun, 30 May',
      arrivalTime: '16:10',
      arrivalDate: 'Sun, 30 May',
      departureAirport: {
        code: 'CCU',
        name: 'Kolkata',
        airport: 'Netaji Subhas Chandra Bose International Airport',
      },
      arrivalAirport: {
        code: 'TRV',
        name: 'Thiruvananthapuram',
        airport: 'Trivandrum International Airport, Terminal T1',
      },
      duration: '4h 45m',
      stops: '1 Stop',
      stopsCount: 1,
      stopLocation: 'MAA',
      stopAirports: [
        {
          code: 'MAA',
          name: 'Chennai',
          airport: 'Chennai International Airport, Terminal T1',
          arrivalTime: '13:40',
          arrivalDate: 'Sun, 30 May',
          departureTime: '14:50',
          departureDate: 'Sun, 30 May',
          layoverDuration: '1h 10m',
        },
      ],
      baggage: {
        cabin: '7 KGS/Adult',
        checkIn: '15 KGS/Adult',
      },
      onTimePercentage: 91,
      priceINR: 14200,
      promoCode: 'TSAIR*',
      discountText: 'Flat 200 off',
      fareOptions: [
        {
          id: 'ai-basic',
          title: 'Economy Standard',
          subtitle: 'Includes full meal service',
          priceINR: 14200,
          badge: 'Standard',
          hoverContent: 'Basic economy fare with complimentary warm meals.',
          features: ['Complimentary Meal', 'Cabin 8kg', 'Check-in 15kg'],
        },
        {
          id: 'ai-prime',
          title: 'Economy Flex',
          subtitle: 'Maximum baggage & priority service',
          priceINR: 16850,
          badge: 'All Inclusive',
          hoverContent: 'Priority check-in, boarding, and increased allowance.',
          features: ['Free Seat Selection', 'Priority Boarding', 'Check-in 25kg'],
        },
      ],
    },
    {
      flightNumber: 'QP-1355',
      airlineName: 'Akasa Air',
      airlineLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwfHx9luzdb066yaUBQZaOJwrvXnlY3qqWWmEf093w3xF8oCFvtRinHUNq&s=10',
      departureTime: '13:25',
      departureDate: 'Sun, 30 May',
      arrivalTime: '15:40',
      arrivalDate: 'Sun, 30 May',
      departureAirport: {
        code: 'PNQ',
        name: 'Pune',
        airport: 'Pune International Airport',
      },
      arrivalAirport: {
        code: 'DEL',
        name: 'New Delhi',
        airport: 'Indira Gandhi International Airport, Terminal T2',
      },
      duration: '2h 15m',
      stops: 'Non-stop',
      stopsCount: 0,
      stopAirports: [],
      baggage: {
        cabin: '7 KGS/Adult',
        checkIn: '15 KGS/Adult',
      },
      onTimePercentage: 96,
      priceINR: 4899,
      promoCode: 'AKASA150',
      discountText: 'Flat ₹150 off',
      fareOptions: [
        {
          id: 'akasa-saver',
          title: 'Saver',
          subtitle: 'Essential flight services',
          priceINR: 4899,
          badge: 'Super Saver',
          hoverContent: 'Great value fare for lightweight travelers.',
          features: ['Cabin Baggage 7kg', 'Standard Seat'],
        },
        {
          id: 'akasa-flexi',
          title: 'Flexi',
          subtitle: 'Meals & flexible seat options',
          priceINR: 6100,
          badge: 'Recommended',
          hoverContent: 'Includes fresh meal box and preferred seat choices.',
          features: ['Free Seat Selection', 'Meal Included', 'Cabin 7kg + Check-in 15kg'],
        },
      ],
    },
    {
      flightNumber: '6E-6324',
      airlineName: 'IndiGo',
      airlineLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB1wabUbuhvcAgjzXGao7BqdMTI7Saymkhs5usV5_gHe6f9XQrGeR12Kk&s=10',
      departureTime: '17:50',
      departureDate: 'Sun, 30 May',
      arrivalTime: '20:05',
      arrivalDate: 'Sun, 30 May',
      departureAirport: {
        code: 'PNQ',
        name: 'Pune',
        airport: 'Pune International Airport',
      },
      arrivalAirport: {
        code: 'DEL',
        name: 'New Delhi',
        airport: 'Indira Gandhi International Airport, Terminal T1',
      },
      duration: '2h 15m',
      stops: 'Non-stop',
      stopsCount: 0,
      stopAirports: [],
      baggage: {
        cabin: '7 KGS/Adult',
        checkIn: '15 KGS/Adult',
      },
      onTimePercentage: 93,
      priceINR: 5999,
      fareOptions: [
        {
          id: 'saver-evening',
          title: 'Saver',
          subtitle: 'Standard evening fare',
          priceINR: 5999,
          badge: 'Best Value',
          hoverContent: 'Standard non-refundable fare.',
          features: ['Cabin Baggage 7kg', 'Standard Seat'],
        },
        {
          id: 'flexi-evening',
          title: 'Flexi Plus',
          subtitle: 'Peace of mind scheduling',
          priceINR: 7399,
          badge: 'Popular',
          hoverContent: 'Modifiable flight schedule without steep penalties.',
          features: ['Free Seat Selection', 'Zero Cancellation Fee', 'Cabin 7kg + Check-in 15kg'],
        },
      ],
    },
  ];
}
